### ISSUE TITLE
Push notification when app is closed / in background showing wrong title and message

### ISSUE THREAD

**Issue by cgosingtian** [JivoChat/JivoSDK-iOS#13]
Followed Push Notification instructions in https://jivochat.github.io/JivoSDK-iOS/tutorials/jivosdk/native_usage_basics

However, the push notifications don't look right when the app is in the background or if closed. 

`func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)` isn't called in the background, but that seems to be where Jivo wants to change the title and the message.

What's the expected way to approach showing Jivo notifications when the app is closed / in background?

**Comment by bronenos** [comment]
This method does handle notifications in foreground mode due to ios rules, and Jivo uses this place as one of entry points, yes

But for background notifications, Localizable strings are used, so please look here for more details:

https://jivochat.github.io/JivoSDK-iOS/documentation/jivosdk/common_project_config
